services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
       
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    environment:
      NODE_ENV: production

      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRATION_TIME_IN_MINUTES: ${JWT_EXPIRATION_TIME_IN_MINUTES}
      JWT_REFRESH_EXPIRATION_TIME_IN_DAYS: ${JWT_REFRESH_EXPIRATION_TIME_IN_DAYS}

      JWT_REFRESH_TOKEN_NAME: ${JWT_REFRESH_TOKEN_NAME}
      JWT_ACCESS_TOKEN_NAME: ${JWT_ACCESS_TOKEN_NAME}

      FRONTEND_URL: http://localhost:${FRONTEND_PORT}
    ports:
      - ${BACKEND_PORT}:3000
    networks:
      - app_network

